// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdeinxdfzqbozfqrmcsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkZWlueGRmenFib3pmcXJtY3NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODE0NTgsImV4cCI6MjA2MzY1NzQ1OH0.8VNMnyToFscTZG0ngDxrQOCBsez5NS-jfGnLhVS9zW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);