name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - name: Build
        run: |
          echo "Checking environment variables..."
          if [ -n "$VITE_GOOGLE_CLIENT_ID" ]; then
            echo "VITE_GOOGLE_CLIENT_ID is set"
          else
            echo "VITE_GOOGLE_CLIENT_ID is NOT set"
          fi
          if [ -n "$VITE_GEMINI_API_KEY" ]; then
            echo "VITE_GEMINI_API_KEY is set"
          else
            echo "VITE_GEMINI_API_KEY is NOT set"
          fi
          npm run build
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}

      - name: Copy index.html to 404.html
        run: cp dist/index.html dist/404.html

      - name: Debug build output
        run: |
          echo "Listing contents of the root directory..."
          ls -la
          echo "Listing contents of the dist directory..."
          ls -R dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./dist
          cname: kii2connect.com
          force_orphan: true
